trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SCAN_PATH: "$(Build.Repository.LocalPath)"

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo "##[command]Obtaining WizCLI from the inter-webs..."
      sudo curl -o /usr/bin/wizcli https://wizcli.app.wiz.io/latest/wizcli
      echo "##[command]Making WizCLI executable"
      sudo chmod +x /usr/bin/wizcli
      /usr/bin/./wizcli auth --id $(WIZ_CLIENT_ID) --secret $(WIZ_CLIENT_SECRET)
  displayName: Download latest WizCLI and Authenticate

- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/./wizcli iac scan --path "$SCAN_PATH"
  displayName: Scan IaC with WizCLI